services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: piholedocker
    environment:
      TZ: 'Europe/Brussels'
      PIHOLE_DNS_: 192.168.1.1   
    volumes:
      - '/home/depechie/pihole:/etc/pihole/'
      - '/home/depechie/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/'
    labels:
      - 'wud.watch.digest=true'
    networks:
      backbone:
        ipv4_address: 10.0.0.3    
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    
  whatsupdocker:
    depends_on:
      - pihole
    container_name: wud
    image: fmartinou/whats-up-docker:5.20.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/fmartinou/whats-up-docker/releases/tag/$${major}.$${minor}.$${patch}'
    networks:
      backbone:
        ipv4_address: 10.0.0.4    
    dns: 10.0.0.3
    ports:
      - 3000:3000    
    restart: unless-stopped      

  calibre:
    depends_on:
      - pihole      
    container_name: calibre
    image: linuxserver/calibre:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /home/depechie/calibre:/config
    labels:
      - 'wud.watch.digest=true'
    networks:
      backbone:
        ipv4_address: 10.0.0.5
    dns: 10.0.0.3        
    ports:
      - 8082:8080
      - 8084:8081
    restart: unless-stopped
    mem_limit: 14336m
    cpus: 6    
    
  calibre-web:
    depends_on:
      - pihole
      - calibre
    container_name: calibre-web
    image: linuxserver/calibre-web:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /home/depechie/calibreweb/config:/config
      - /home/depechie/calibre/books:/books
    labels:
      - 'wud.watch.digest=true'
    networks:
      backbone:
        ipv4_address: 10.0.0.6
    dns: 10.0.0.3            
    ports:
      - 8083:8083
    restart: unless-stopped
    mem_limit: 14336m
    cpus: 6

  handbrake:
    depends_on:
      - pihole
    image: jlesage/handbrake
    container_name: handbrake    
    environment:
      TZ: 'Europe/Brussels'
    volumes:
      - "/home/depechie/handbrake/config:/config"
      - "/home/depechie/handbrake/watch:/watch"
      - "/home/depechie/handbrake/output:/output"
      - "/home/depechie/handbrake/storage:/storage"
    labels:
      - 'wud.watch.digest=true'
    networks:
      backbone:
        ipv4_address: 10.0.0.7
    dns: 10.0.0.3
    ports:
      - 5800:5800    
    restart: unless-stopped
    mem_limit: 14336m
    cpus: 6      

  emby:
    image: emby/embyserver
    container_name: emby
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=1000 # The GID to run emby as (default 2)
      - GIDLIST=44,107 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /home/depechie/emby/config:/config
      - /home/depechie/emby/movies:/mnt/movies
      - /home/depechie/emby/series:/mnt/series
      - /home/depechie/emby/anime:/mnt/anime
      - /home/depechie/emby/concerts:/mnt/concerts
    ports:
      - 8096:8096 # HTTP port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    restart: unless-stopped
    
networks:
  backbone:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: backbone
    ipam:
      config:
        - subnet: 10.0.0.0/27