version: '3'

services:
  sbfspot:
    image: nakla/sbfspot:latest
    container_name: sbfspot
    network_mode: host
    volumes:            
      - /home/depechie/sbfspot/config:/etc/sbfspot
      - /home/depechie/sbfspot/data:/var/sbfspot
    environment:
      TZ: Europe/Brussels
      ENABLE_SBFSPOT: 1
      SBFSPOT_INTERVAL: 600
      ENABLE_SBFSPOT_UPLOAD: 1
      DB_STORAGE: sqlite
      CSV_STORAGE: 1
      MQTT_ENABLE: 0
      QUIET: 0
      SBFSPOT_ARGS: -d0 -v2
      INIT_DB: 0
    restart: unless-stopped